apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
      - name: notes-api
        image: gcr.io/gcpk8-462408/notes-api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: notes-api-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: notes-api-service
spec:
  type: LoadBalancer
  selector:
    app: notes-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
