name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build and Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{secrets.DOCKERHUB_USERNAME}}/notes-api:latest
        load: true

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Deploy to Azure
      uses: Azure/webapps-deploy@v3
      with:
        app-name: notes-api
        images: ${{secrets.DOCKERHUB_USERNAME}}/notes-api:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{secrets.GCP_SA_KEY}}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{secrets.GCP_PROJECT_ID}}

    - name: Authenticate Docker to GCR
      run: |
        gcloud auth configure-docker

    - name: Tag and Push Image to GCR
      run: |
        docker tag ${{secrets.DOCKERHUB_USERNAME}}/notes-api:latest gcr.io/${{secrets.GCP_PROJECT_ID}}/notes.api:latest
        docker push gcr.io/${{secrets.GCP_PROJECT_ID}}/notes.api:latest

    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials scribbly-cluster --zone asia-south2-a --project ${{secrets.GCP_PROJECT_ID}}

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s-deployment.yaml